package com.volmit.fulcrum.resourcepack;

public enum KnownPath
{
	/**
	 * Structures
	 */
	STRUCTURES__ENDCITY,
	STRUCTURES__FOSSILS,
	STRUCTURES__IGLOO,
	STRUCTURES__MANSION,
	
	/**
	 * Shaders
	 */
	SHADERS__POST,
	SHADERS__PROGRAM,
	
	/**
	 * Models
	 */
	MODELS__BLOCK,
	MODELS__ITEM,
	
	/**
	 * Textures
	 */
	TEXTURES__BLOCKS,
	TEXTURES__COLORMAP,
	TEXTURES__EFFECT,
	TEXTURES__ENTITY,
	TEXTURES__ENTITY__ARMORSTAND,
	TEXTURES__ENTITY__BANNER,
	TEXTURES__ENTITY__BEAR,
	TEXTURES__ENTITY__BED,
	TEXTURES__ENTITY__BOAT,
	TEXTURES__ENTITY__CAT,
	TEXTURES__ENTITY__CHEST,
	TEXTURES__ENTITY__COW,
	TEXTURES__ENTITY__CREEPER,
	TEXTURES__ENTITY__ENDERCRYSTAL,
	TEXTURES__ENTITY__ENDERDRAGON,
	TEXTURES__ENTITY__ENDERMAN,
	TEXTURES__ENTITY__GHAST,
	TEXTURES__ENTITY__HORSE,
	TEXTURES__ENTITY__HORSE__ARMOR,
	TEXTURES__ENTITY__ILLAGER,
	TEXTURES__ENTITY__LLAMA,
	TEXTURES__ENTITY__LLAMA__DECOR,
	TEXTURES__ENTITY__PARROT,
	TEXTURES__ENTITY__PIG,
	TEXTURES__ENTITY__PROJECTILES,
	TEXTURES__ENTITY__RABBIT,
	TEXTURES__ENTITY__SHEEP,
	TEXTURES__ENTITY__SHIELD,
	TEXTURES__ENTITY__SHULKER,
	TEXTURES__ENTITY__SKELETON,
	TEXTURES__ENTITY__SLIME,
	TEXTURES__ENTITY__SPIDER,
	TEXTURES__ENTITY__VILLAGER,
	TEXTURES__ENTITY__WITHER,
	TEXTURES__ENTITY__WOLF,
	TEXTURES__ENTITY__ZOMBIE,
	TEXTURES__ENTITY__ZOMBIE_VILLAGER,
	TEXTURES__ENVIRONMENT,
	TEXTURES__FONT,
	TEXTURES__GUI,
	TEXTURES__GUI__ADVANCEMENTS,
	TEXTURES__GUI__ADVANCEMENTS__BACKGROUNDS,
	TEXTURES__GUI__CONTAINER,
	TEXTURES__GUI__CONTAINER_CREATIVE_INVENTORY,
	TEXTURES__GUI__TITLE,
	TEXTURES__ITEMS,
	TEXTURES__MAP,
	TEXTURES__MISC,
	TEXTURES__MODELS,
	TEXTURES__MODELS__ARMOR,
	TEXTURES__PAINTING,
	TEXTURES__PARTICLE;

	@Override
	public String toString()
	{
		return name().toLowerCase().replaceAll("__", "/");
	}
}
