package com.volmit.fulcrum.custom;

public enum CompilerFlag
{
	VERBOSE,
	OVERBOSE,
	PNG_COMPRESSION,
	JSON_MINIFICATION,
	PREDICATE_CYCLING,
	CONCURRENT_REGISTRY,
	REGISTER_DEBUG_ITEMS,
	PREDICATE_MINIFICATION;
}
